//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSE.WinForms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class ItemColorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ItemColorSettings defaultInstance = ((ItemColorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ItemColorSettings())));
        
        public static ItemColorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3359432240")]
        public uint FurnitureColor {
            get {
                return ((uint)(this["FurnitureColor"]));
            }
            set {
                this["FurnitureColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3369370404")]
        public uint GyroidColor {
            get {
                return ((uint)(this["GyroidColor"]));
            }
            set {
                this["GyroidColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3372155007")]
        public uint DiaryColor {
            get {
                return ((uint)(this["DiaryColor"]));
            }
            set {
                this["DiaryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3358094506")]
        public uint ClothesColor {
            get {
                return ((uint)(this["ClothesColor"]));
            }
            set {
                this["ClothesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3366251704")]
        public uint SongColor {
            get {
                return ((uint)(this["SongColor"]));
            }
            set {
                this["SongColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3366251752")]
        public uint PaperColor {
            get {
                return ((uint)(this["PaperColor"]));
            }
            set {
                this["PaperColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3361041199")]
        public uint TrashColor {
            get {
                return ((uint)(this["TrashColor"]));
            }
            set {
                this["TrashColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3372204235")]
        public uint ShellColor {
            get {
                return ((uint)(this["ShellColor"]));
            }
            set {
                this["ShellColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3369967837")]
        public uint FruitColor {
            get {
                return ((uint)(this["FruitColor"]));
            }
            set {
                this["FruitColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3367742621")]
        public uint TurnipColor {
            get {
                return ((uint)(this["TurnipColor"]));
            }
            set {
                this["TurnipColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3367691070")]
        public uint CatchableColor {
            get {
                return ((uint)(this["CatchableColor"]));
            }
            set {
                this["CatchableColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3367876459")]
        public uint QuestItemColor {
            get {
                return ((uint)(this["QuestItemColor"]));
            }
            set {
                this["QuestItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3372197120")]
        public uint ItemColor {
            get {
                return ((uint)(this["ItemColor"]));
            }
            set {
                this["ItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3357446399")]
        public uint RaffleTicketColor {
            get {
                return ((uint)(this["RaffleTicketColor"]));
            }
            set {
                this["RaffleTicketColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3365486656")]
        public uint WallpaperCarpetColor {
            get {
                return ((uint)(this["WallpaperCarpetColor"]));
            }
            set {
                this["WallpaperCarpetColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3360767279")]
        public uint FossilColor {
            get {
                return ((uint)(this["FossilColor"]));
            }
            set {
                this["FossilColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3363930497")]
        public uint ToolColor {
            get {
                return ((uint)(this["ToolColor"]));
            }
            set {
                this["ToolColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3364570387")]
        public uint TreeColor {
            get {
                return ((uint)(this["TreeColor"]));
            }
            set {
                this["TreeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3355475968")]
        public uint WeedColor {
            get {
                return ((uint)(this["WeedColor"]));
            }
            set {
                this["WeedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3370936248")]
        public uint FlowerColor {
            get {
                return ((uint)(this["FlowerColor"]));
            }
            set {
                this["FlowerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3355443200")]
        public uint RockColor {
            get {
                return ((uint)(this["RockColor"]));
            }
            set {
                this["RockColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3366137647")]
        public uint MoneyRockColor {
            get {
                return ((uint)(this["MoneyRockColor"]));
            }
            set {
                this["MoneyRockColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3362140928")]
        public uint SignboardColor {
            get {
                return ((uint)(this["SignboardColor"]));
            }
            set {
                this["SignboardColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3372220160")]
        public uint MoneyColor {
            get {
                return ((uint)(this["MoneyColor"]));
            }
            set {
                this["MoneyColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3366295701")]
        public uint HouseObjectColor {
            get {
                return ((uint)(this["HouseObjectColor"]));
            }
            set {
                this["HouseObjectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4286019447")]
        public uint BuildingColor {
            get {
                return ((uint)(this["BuildingColor"]));
            }
            set {
                this["BuildingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3366151936")]
        public uint ParchedFlowerColor {
            get {
                return ((uint)(this["ParchedFlowerColor"]));
            }
            set {
                this["ParchedFlowerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3355484320")]
        public uint WateredFlowerColor {
            get {
                return ((uint)(this["WateredFlowerColor"]));
            }
            set {
                this["WateredFlowerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3365509631")]
        public uint PatternColor {
            get {
                return ((uint)(this["PatternColor"]));
            }
            set {
                this["PatternColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3360509235")]
        public uint WiltedFlowerColor {
            get {
                return ((uint)(this["WiltedFlowerColor"]));
            }
            set {
                this["WiltedFlowerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3717831065")]
        public uint OccupiedColor {
            get {
                return ((uint)(this["OccupiedColor"]));
            }
            set {
                this["OccupiedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3372154880")]
        public uint InvalidColor {
            get {
                return ((uint)(this["InvalidColor"]));
            }
            set {
                this["InvalidColor"] = value;
            }
        }
    }
}
